FILE = COMMENT* MAINCARD* SBCARD*
COMMENT = #"\/\/((?!\r?\n).)*" <LINEBREAK>
LINEBREAK = #"\r?\n"
MAINCARD = COUNT <SPACE> <LEFT_BRACKET> SET <RIGHT_BRACKET> <SPACE> CARDNAME <LINEBREAK>
COUNT = #"\d+"
SPACE = ' '
LEFT_BRACKET = '['
RIGHT_BRACKET = ']'
SET = #"\w*"
CARDNAME = #"((?!\r?\n).)*"
SBCARD = <SB_DELIM> <SPACE> COUNT <SPACE> <LEFT_BRACKET> SET <RIGHT_BRACKET> <SPACE> CARDNAME <LINEBREAK>
SB_DELIM = "SB: "
